apiVersion: v1
kind: Service
metadata:
  name: {{ include "mirror-gui.fullname" . }}
  labels:
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "mirror-gui.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "mirror-gui.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
